In [3]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#reading the dataset
data=pd.read_csv('/content/Salary_dataset.csv')
data.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [5]:
#droping the column Unnamed 0
data=data.drop('Unnamed: 0',axis=1)
data.head()

   YearsExperience   Salary
0              1.2  39344.0
1              1.4  46206.0
2              1.6  37732.0
3              2.1  43526.0
4              2.3  39892.0

In [6]:
#shape of the dataset
data.shape

(30, 2)

In [7]:
#check for null values
data.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [8]:
data.describe()

       YearsExperience         Salary
count        30.000000      30.000000
mean          5.413333   76004.000000
std           2.837888   27414.429785
min           1.200000   37732.000000
25%           3.300000   56721.750000
50%           4.800000   65238.000000
75%           7.800000  100545.750000
max          10.600000  122392.000000

In [9]:
#spliting in x and y
y = data['Salary']
x = data.drop(['Salary'],axis=1)

In [10]:
y.shape

(30,)

In [11]:
#from sklearn importing train split and Linear regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
#Spliting x and y into training and test dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=50)

In [13]:
x_train.head()

    YearsExperience
25              9.1
20              6.9
29             10.6
21              7.2
10              4.0

In [14]:
#traing the model
reg=LinearRegression()
model=reg.fit(x_train, y_train)

In [15]:
#predicting values for test dataset
y_pred=model.predict(x_test)
y_pred

array([ 74939.5855115 ,  55035.35379354, 122330.6134114 ,  59774.45658353,
        80626.50885949,  81574.32941748])

In [16]:
#checking the model performance
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r_score = r2_score(y_test, y_pred)
print("Mean Squared Error :", mse)
print("Mean Absolute Error :", mae)
print("R2 Score :", r_score)

Mean Squared Error : 52522472.85879592
Mean Absolute Error : 5551.67759835332
R2 Score : 0.882467963516984

The model has a R2 score closer to 1 and MSE, MAE has a higher value.

In [17]:
#function to predict for new data
def predict_sal(years):
  x=np.array([years])
  x=x.reshape(1,-1)
  y_pred=model.predict(x)
  return y_pred[0].round(2)

In [18]:
data.tail()

    YearsExperience    Salary
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [19]:
print(f'The predicted salary:{predict_sal(9.1)}')

The predicted salary:110008.95

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(